### ISSUE TITLE
Find a better ratio

### ISSUE THREAD

**Issue by Sti2nd** [Sti2nd/custom-guess-who#1]
Resizing to 121:98 is a pretty weird ratio (cumbersome to write). 15:12 is fairly close (121 - 1 : 98 - 2). Or one could test how 3:2 looks (15 : 12 - 2).

**Comment by jhale1805** [comment]
I'm using this to make a game for a Christmas present, and have had to adjust most of the parameters. I'm using a 2020 version of the game by Hasbro and using pictures with a 22:32 ratio with secret card sizes of 73mm (height) x 36mm (width) and face card sizes of 28mm (width) x 50mm (height)* works well for me.

* I know I swapped the order in this reporting. I'm just following the order that's in the code.

**Comment by Sti2nd** [comment]
Cool that you found the code useful @jhale1805 ! And thanks for the PR!

This game is in many versions all around the globe, it seems, so I think the best improvement is to make it easier to configure. Updated an issue for it here #3. I might as well merge your PR since that is the latest version of the game 😁 And the blank card feature is nice!
